server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rewards
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: S101siva45@@
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.H2Dialect
    show-sql: true
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    root: INFO
    com.rewards: DEBUG   # detailed logs for your package
    org.springframework.web: INFO
  file:
    name: logs/rewards-api.log

rewards:
  min-amt-spend-for-points: 50
  min-amt-spend-for-bonus: 100
  multiplier: 2

